# Generated by Django 4.2.6 on 2023-11-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_options_alter_version_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'permissions': (('can_cancel_entry_publication', 'Can cancel entry publication'), ('can_change_entry_description', 'Can change entry description')), 'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_change_product_description', 'Can change product description'), ('can_change_product_category', 'Can change product category')), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
