# Generated by Django 4.2.6 on 2023-11-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_alter_blogentry_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'permissions': (('set_published', 'description, published'),), 'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('set_published', ' desk, published, category'),), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
